contact/urls.py
from django.urls import path
from .views import ContactPageView

app_name = "contact" 

urlpatterns = [
    path("", ContactPageView.as_view(), name = "form"),
]

menu/urls.py
from django.urls import path
from . import views 

app_name = "menu" 

urlpatterns = [
    path("", views.dish_list, name = "dish_list"),
]

navigation/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy
from .views import HomePageView, AboutPageView


app_name = "navigation" 


urlpatterns = [
    path("", HomePageView.as_view(), name = "home"),
    path(gettext_lazy("about/"), AboutPageView.as_view(), name ="about"),
]

negus/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy


urlpatterns = [
    path("admin/", admin.site.urls),
]
urlpatterns += i18n_patterns(
    path("", include("navigation.urls", namespace = "navigation")),
    path(gettext_lazy("menu/"), include("menu.urls", namespace = "menu")),
    path(gettext_lazy("contact/"), include("contact.urls", namespace = "contact")), 
    path(gettext_lazy("reservation/"), include("reservation.urls", namespace = "reservation")),
)

reservation/urls.py
from django.urls import path
from .views import ReservationPageView

app_name = "reservation" 

urlpatterns = [
    path("", ReservationPageView.as_view(), name = "reservation_form"),
]

menu/models.py
from django.db import models
from parler.models import TranslatableModel, TranslatedFields

"""
The menu of the negus restaurant consists of dishes that are 
organized into different categories.
Each dish has a name, discription, prince, etc. 

Two models: Category and Dish 
- Category
    + name field
    + slug unique field (implies the creation of an index)
- Dish 
    + category ForeignKey (many-to-one relationship, which means a dish belongs to one category only, but a category contains  multiple dishes)
    + name 
    + slug 
    + description
    + price 
"""
# 
class Category(TranslatableModel):
    """
    """
    translations = TranslatedFields(
        name     = models.CharField(max_length = 200, db_index = True),
        slug     = models.SlugField(max_length = 200, db_index = True, unique = True) 
    )
    position    = models.PositiveIntegerField(unique = True)
    #
    class Meta:
        """
        """
        ordering            = ("position",)
        verbose_name        = "category"
        verbose_name_plural = "categories"
   
    #
    def __str__(self):
        """
        """ 
        return self.name 


#
class Dish(TranslatableModel):
    """
    """
    translations    = TranslatedFields(
        name        = models.CharField(max_length = 200, db_index = True),
        slug        = models.SlugField(max_length = 200, db_index = True), 
        description = models.TextField(blank = True)
    )
    category = models.ForeignKey(Category, related_name = "dishes", on_delete = models.CASCADE)
    price       = models.DecimalField(max_digits = 5, decimal_places = 2)
    
    #
    #class Meta:
    #    """
    #    """
        #ordering        = ("name", )
        #index_together  = (("id", "slug"),)
    
    #
    def __str__(self):
        """
        """
        return self.name 

reservation/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms 

class ContactForm(forms.Form):
    """
    """
    full_name   = forms.CharField(widget = forms.TextInput(attrs = {"placeholder":"Full name"}))
    email       = forms.EmailField(widget = forms.TextInput(attrs = {"placeholder":"Email"}))
    message     = forms.CharField(widget = forms.Textarea(attrs = {"placeholder":"Message"}))
    
    # custom validation 
    def clean_email(self, *args, **kwargs):
        """
        """
        email   = self.cleaned_data.get("email")
        print(email)
        if email.endswith(".edu"):
            raise forms.ValidationError("Sorry, but this is not a valid email! Please, don't use \".edu\"")
        return email

reservation/forms.py
from django import forms 

class ReservationForm(forms.Form):
    """
    """
    # 
    OPTIONS                     = [("email", "email"),
                                   ("sms", "sms")] 

    #
    number_of_people            = forms.IntegerField()
    date                        = forms.DateField() 
    time                        = forms.TimeField()

    #
    first_name                  = forms.CharField()
    last_name                   = forms.CharField()
    email                       = forms.EmailField(initial = "antho.4@hotmail.fr")
    phone                       = forms.CharField() 
    preferred_communication     = forms.ChoiceField(choices = OPTIONS, widget = forms.RadioSelect())

    # custom validation 
    def clean_email(self, *args, **kwargs):
        """
        """
        email   = self.cleaned_data.get("email")
        print(email)
        if email.endswith(".edu"):
            raise forms.ValidationError("Sorry, but this is not a valid email! Please, don't use \".edu\"")
        return email

contact/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import ContactForm

class ContactPageView(View):
    form_class      = ContactForm
    template_name   = "contact/form.html"

    def get(self, request):
        """
        """
        return render(request, self.template_name, {"form":self.form_class()})

    def post(self, request):
        """
        """
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            mail_sent = bound_form.send_mail()
            if mail_sent:
                # shortcut for add_message 
                success(request, "Email successfully send!")
                return redirect("")
        return render(request, self.template_name, {"form":bound_form})

menu/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Dish

"""
To display the menu, a view is created to 
list all dishes or filter dishes by a given category
"""

#
def dish_list(request, category_slug = None):
    """
    """
    category    = None
    # List of all the categories (available in the database)
    categories  = Category.objects.all() 
    # List of all the dishes (available in the database) 
    dishes      = Dish.objects.all() 
    # 
    if category_slug:
        #
        category    = get_object_or_404(Category, slug = category_slug)
        #
        dishes      = dishes.filter(category = category)
    #
    template_name   = "menu/dish/list.html" 
    #
    context         = {"category":category, "categories":categories, "dishes":dishes} 
    #
    return render(request, template_name, context)

navigation/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import get_template
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "navigation/index.html"

class AboutPageView(TemplateView):
    template_name = "navigation/about.html"

"""
def home_page(request):
    context         = {} 
    template        = "index.html"
    template_object = get_template(template)
    return HttpResponse(template_object.render(context))
"""

negus/views.py
from django.shortcuts import render

# Create your views here.

reservation/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import ReservationForm

class ReservationPageView(View):
    form_class      = ReservationForm
    template_name   = "reservation/reservation_form.html"

    def get(self, request):
        """
        """
        return render(request, self.template_name, {"form":self.form_class()})

    def post(self, request):
        """
        """
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            mail_sent = bound_form.send_mail()
            if mail_sent:
                # shortcut for add_message 
                success(request, "Email successfully send!")
                return redirect("")
        return render(request, self.template_name, {"form":bound_form})

contact/templates/contact/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% load l10n %}
{% load tz %}
{% block meta %}
<title>{% trans "Contact Us" %} | {% trans "Negus restaurant" %}</title>
{% endblock %}

{% block content %} 
<div class = "container-fluid mt-5">
    <div class = "row font-paragraph"> 
        <div class = "flag">
            <div class = "first-color"></div> 
            <div class = "second-color"></div>
            <div class = "third-color"></div>
            <div class = "col-10 col-md-6 mx-auto mt-5 background-white border border-primary">
                <h2 class = "my-4 text-center font-heading font-25 text-inline text-success">{% trans "Contact Us" %}</h2>
                <h4 class = "col-8 mx-auto font-heading text-center">{% trans "Any questions? Would you like some information?" %}</h4>
                <form class = "form-horizontal" action = "{% url 'contact:form' %}" method = "post">
                    {% csrf_token %}
                    <div class = "form-row">
                        <div class = "form-group col-12">
                        {{ form.full_name |as_crispy_field }}
                        </div>
                        <div class = "form-group col-12">
                        {{ form.email |as_crispy_field }}
                        </div>
                        <div class = "form-group col-12 h-max-100">
                        {{ form.message |as_crispy_field }}
                        </div>
                        <button class = "btn btn-primary" type = "submit">{% trans 'Contact Us'%}</button>
                    </div>
                </form>
            </div>
         </div>    
    </div>
</div>
{% endblock %}

menu/templates/menu/dish/list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load l10n %}
{% load tz %}

{% block meta %}
<title>{% trans "Menu" %} | {% trans "Negus restaurant" %}</title>
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
    <div class = "container-fluid bg-img-1 text-center">
        <h1 class = "mt-6 font-heading font-30 font-weight-600 text-success text-inline">{% trans "Our menu" %}</h1>
            {% for each_category in categories %}
            <h2 class = "my-4 font-heading text-uppercase">{{ each_category.name }}</h2>
                    <div class = "row mx-auto border border-primary">
                        {% for each_dish in dishes %}
                            {% if each_dish.category == each_category %}
                                <div class = "col-12 col-md-6 my-2 px-5">
                                    <div class = "linewrapper">
                                        <h3 class = "text-capitalize">{{ each_dish.name }}</h3>
                                        <div class = "middle-dots"></div>
                                        <em>{{ each_dish.price }}</em>
                                    </div>
                                    </p>{{ each_dish.description }}</p> 
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
            {% endfor %}
            <a href="#">#</a>
    </div>
{% endblock %}

navigation/templates/navigation/about.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load l10n %}
{% load tz %}

{% block meta %}
<title>{% trans "About us"%} | {% trans "Negus restaurant" %}</title>
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
<main>
    <article class = "container-fluid vh-min-100">
        <div class = "row equal text-center font-paragraph font-12 line-height-10"> 
            <div class = "col-12 mt-6 mb-3 font-heading">
                <h1 class = "mb-2 font-30 font-weight-600 text-success text-inline">{% trans "Negus restaurant" %}</h1>
                <h4 class = "my-4 font-weight-400">{% trans "A corner of Ethiopia in the midst of Paris" %}</h4>    
            </div>
            <div class = "col-md-6 px-5">
                <div = "wrapper height-100">
                    <div class = "circle circle-left">
                        <img class = "image-resize-80" src = "{% static 'images/000000.jpg' %}" alt = "">
                    </div>
                    <section class = "text-justify">
                        <p>
                        {% trans "The Negus is a small family-run restaurant which brings a part of Ethiopia in the midst of Paris. The Ethiopian cuisine is a delight for everyone - particularly through colorful vegetarian and vegan dishes. Gluten intolerance will no longer be a problem with our 100% teff injeras. A selection of wine and traditional Ethipian beers can also be served to accompany our food." %}
                        </p>
                     </section>
                </div>
            </div>
            <div class = "col-md-6 mb-5 px-5 border-left border-danger">
                <div class = "wrapper height-100">
                    <div class = "circle circle-right">
                        <img class = "image-resize-80" src = "{% static 'images/0005.jpg' %}" alt = "">                      
                    </div>
                    <section class = "text-justify">
                        <p>
                        {% trans "We're Sisay and Sitina. Both of us were born in Ethiopia, but we met 29 years ago in Paris. Together we built this restaurant that we love to call our home. We have tried our best to make people discover a bit of our country of orign. It does not end with the food, as we provide historical and cultural lectures on Sundays." %}<br>{% trans "There is only one thing left... Come treat yourself!" %}
                        </p>
                    </section>        
                </div>
            </div>
            <div class = "offset-3 col-3 font-paragraph">
                <h6>
                   <a href = "{% url 'menu:dish_list' %}" class = "button px-2 py-2 text-uppercase"><b>{% trans "see our menu" %}</b></a></h6> 
            </div>
            <div class = "col-3 font-paragraph">
                <h6>
                   <a href = "{% url 'reservation:reservation_form' %}" class = "button px-2 py-2 text-uppercase"><b>{% trans "make a reservation" %}</b></a> 
            </div>
        </div>
    </article>
    <article class = "container-fluid vh-min-100">  
        <div class = "row text-center">
		<!--
            <div class = "flag">
                 <div class = "col-12 mt-2 lato">
                    <h3 class = "my-2 font-weight-600 text-primary">{% trans "What do people say about us?" %}</h3>
                </div> 
                 <div class = "first-color">
                     
                 </div> 
                 <div class = "second-color">
                     <img src = "{% static 'images/1000.svg' %}" alt="" />
                 </div>
                 <div  class = "third-color">
                     
                 </div>
            </div>    
        </div>
 -->
        <!--
        <div class = "row mx-auto text-center karla">
            <div class = "col-12 mt-2 lato">
                <h3 class = "my-2 font-weight-600 text-success">{% trans "What do people say about us?" %}</h3>
            </div> 
            <section class = "col-12 col-md-4 text-justify">
                <h4 class = "text-center">Excellent first Ethipian food experience</h4>
                <p>
                We came upon this cozy restaurant while searching for vegetarian options 
                and we were certainly not disappointed. The owner was very welcoming and 
                made the meal a fun experience. There are a variety of meat options but 
                our vegetarian choices were fabulous. We left with a new found love of Ethiopian food.
                </p>
                <p class = "text-center">Florence C.<br> Ottawa (Canada)</p>     
            </section>
            <section class = "col-12 col-md-4 text-justify">
                <h4 class = "text-center">Plus qu'un diner au restaurant</h4>
                <p>Plus qu'un diner au restaurant, venir manger au NEGUS c'est s'offrir le temps d'une soirée un aller-retour pour Addis Abeba ! Un véritable voyage pour les papilles, les oreilles, les yeux et... les mains !
                J'ai retrouvé l'ambiance de mes repas lors de mon voyage en Ethiopie, l'injera est plus douce au palais que celle que l'on peut manger sur place, mais je ne m'en plaindrais pas...
                Les garnitures et sauces sont excellentes. Il ne manque plus que le Tej et les azmaris !
                L'accueil de Sisay est exceptionnel. Si après ça vous n'avez pas envie d'aller découvrir ce merveilleux pays qu'est l'Ethiopie...</p>   
                <p class = "text-center">Philipe B.<br>Billiere (France)</p>
            </section>
            <section class = "col-12 col-md-4 text-center">
                <h4>Small, homely, intimate taste of Ethiopia in Paris </h4> 
                <p class = "text-justify">Brought the olds here for their first experience of Ethiopian food. Superb injera to share, Ethiopian beer and a great atmosphere. Not too spicy, though I think we got the beginner's version, and you could probably ask for a bit more chilli if required. We had fresh mango and cinnamon for desert, and traditionally served Ethiopian coffee. The venue is a blink-and-you'll-miss-it adapted living room covered in pictures and artefacts from Ethiopia. Highly recommended.i</p>   
                <p>Natalie<br>Townsville (Australia) </p>
            </section>
            <a href="https://auroreinparis.com/2012/07/16/jai-teste-un-restaurant-ethiopien-le-negus/">Blog about the negus...</a>
             <a href="https://lesdelicesdevanessa.com/2009/12/20/le-negus-le-restaurant-ethiopien/">Blog about the negus...</a>
                   </div>
                -->
    </article>
</main>
{% endblock %}

navigation/templates/navigation/index.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}
{% load l10n %}
{% load tz %}

{% block meta %}
<title>{% trans "Negus restaurant" %}</title>
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
<div class = "top-content">
    <div class = "row no-gutters">
        <div class = "col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">     
            <div id = "carousel-example" class = "carousel slide" data-ride = "carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example" data-slide-to="1"></li>
                    <li data-target="#carousel-example" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'images/0300.jpg' %}" class="d-block w-auto h-100" alt="img1">
                            <div class="carousel-caption">
                                <h1 class="wow fadeInLeftBig">Carousel Template with Bootstrap 4</h1>
                                <div class="description wow fadeInUp">
                                    <p>
                                    This is a free Carousel template made with the Bootstrap 4 framework.
                                    Check it out now. Download it, customize and use it as you like!
                                    </p>
                                </div>
                            </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/0500.jpg' %}" class="d-block w-auto h-100" alt="img2">
                        <div class="carousel-caption">
                            <h1 class="wow fadeInLeftBig">This is Slide 2 of our Carousel</h1>
                            <div class="description wow fadeInUp">
                                <p>
                                You can download this free template
                                on <a href="https://azmind.com" target="_blank">AZMIND</a>.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/0600.jpg' %}" class="d-block w-auto h-100" alt="img3">
                        <div class="carousel-caption">
                            <h1 class="wow fadeInLeftBig">This is Slide 3, the Last One</h1>
                            <div class="description wow fadeInUp">
                                <p>
                                After you download it, you can customize and use 
                                it as you like. That's great!
                                </p>
                            </div>
                        </div>
                    </div>
            </div>
            <a class="carousel-control-prev" href="#carousel-example" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-example" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
{% endblock %}

negus/templates/base.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load extra_tags %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <!-- meta tags -->
        <meta charset = "utf-8">
        <meta name = "viewport" content = "width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv = "x-ua-compatible" content = "ie=edge">
        {% block meta %}
        {% endblock %}
        <!-- meta tags --> 
        <!-- css -->
        <link rel = "stylesheet" title = "base css file" type = "text/css" href = "{% static 'css/bootstrap/base.css'%}"/>
        <link rel = "stylesheet" href = "https://use.fontawesome.com/releases/v5.0.8/css/all.css">
        {% block css %}
        {% endblock %}
        <!-- css -->
    </head>
    <body>
        <header>
            <nav class = "navbar navbar-expand-lg bg-dark fixed-top justify-content-center font-heading font-13">
                <a class = "navbar-brand text-success" href="{% url 'navigation:home' %}">Negus</a>
                <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarSupportedContent" aria-controls = "navbarSupportedContent" aria-expanded = "false" aria-label = "Toggle navigation">
            <span class = "navbar-toggler-icon"></span>
                </button>

                <div class = "collapse navbar-collapse" id = "navbarSupportedContent">
                    <ul class = "navbar-nav mx-auto">
                        <li class = "nav-item"><a class = "nav-link text-warning" href = "{% url 'menu:dish_list' %}">{% trans "Menu" %}<span class="sr-only">(current)</span></a></li>
                        <li class = "nav-item"><a class = "nav-link text-warning" href = "{% url 'navigation:about' %}">{% trans "About Us" %}</a></li>
                        <li class = "nav-item"><a class = "nav-link text-warning" href = "{% url 'reservation:reservation_form' %}">{% trans "Reservations" %}</a></li>
                        <li class = "nav-item"><a class = "nav-link text-warning" href = "{% url 'contact:form' %}">{% trans "Contact Us" %}</a></li>
                    </ul>
                    <ul class = "navbar-nav">
                        <li class = "nav-item dropdown"><a class = "nav-link dropdown-toggle text-danger" href = "#" id = "navbarDropdown" role = "button" data-toggle = "dropdown" aria-haspopup = "true" aria-expanded = "false">{% trans "Language"%}</a>
                            <div class = "dropdown-menu" aria-labelledby = "navbarDropdown">
                                {% get_available_languages as languages %}
                                {% for lang in languages %}
                                    {% language lang.0 %}
                                    <a class = "dropdown-item" href = "{% change_lang request lang.0 %}">{{ lang.1 }}</a>
                                    {% endlanguage %}
                                {% endfor %} 
                            </div>
                        </li> 
                    </ul>
                </div>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
        
        <footer>
            <div class = "container-fluid text-center text-light bg-dark">
                <div class = "row mx-auto pt-4">
                    <div class = "col-md-4 px-4">
                        <h4 class = "mb-3 font-heading text-capitalize text-success text-between-line text-between-line-success text-between-line-50">{% trans "negus restaurant" %}</h4>
                        <p class = "font-paragraph">{% trans "Come treat yourself with some Ehiopian cusine" %}</p>
                        <button class = "btn btn-outline-primary rounded-0 font-09 font-paragraph text-uppercase" type = "button">{% trans "make a reservation" %}</button>
                        <p class = "mt-2 font-paragraph">{% trans "or check us out" %}</p>
                        <ul class = "list-unstyled list-inline">
                            <li class = "list-inline-item logos"><a href = "https://www.facebook.com/pages/category/Ethiopian-Restaurant/Restaurant-%C3%A9thiopien-Le-Negus-330618804391/"><i class = "fab fa-facebook-f"></i></a></li>
                            <li class = "list-inline-item logos"><a href = "https://www.tripadvisor.com/Restaurant_Review-g187147-d3726831-Reviews-Le_Negus-Paris_Ile_de_France.html"><i class = "fab fa-tripadvisor"></i></a></li>
                        </ul>
                    </div>
                    <div class = "col-md-4 px-4 font-paragraph">
                        <h4 class = "mb-3 font-heading text-capitalize text-warning text-between-line text-between-line-warning text-between-line-50">{% trans "opening hours" %}</h4>
                        <ul class = "pl-0 list-unstyled">
                            <li class = "font-heading text-capitalize">{% trans "monday - friday" %}</li>
                            <ul class = "pl-0 list-unstyled">                                
                                <li>12 am - 2 pm</li> 
                                <li>07 pm - 12am</li>
                            </ul>
                            <li class = "mt-2 font-heading text-capitalize">{% trans "saturday - sunday" %}</li>
                            <ul class = "pl-0 list-unstyled">
                                <li>12 am - 2 pm</li> 
                                <li>07 pm - 12am</li> 
                            </ul>
                        </ul>
                    </div>
                    <div class = "col-md-4 px-4">
                        <h4 class = "font-heading text-capitalize text-danger text-between-line text-between-line-danger text-between-line-50">{% trans "contact us" %}</h4>
                        <p></p>
                        <h5 class = "font-heading text-capitalize">{% trans "address" %}</h5>
                        <p class = "font-paragraph">52 rue de Montreuil,<br>75011 Paris, France</p>
                        <h5 class = "font-heading text-capitalize">{% trans "phone number" %}</h5> 
                        <p class = "font-paragraph">01 43 48 91 52</p>
                    </div>
                    <div class = "col-12 font-paragraph">
                        <h3 class = "width-40 mx-auto pt-3 font-11 border-top border-primary">{% trans "negus restaurant" %} &copy; 2019</h3>
                        <h2 class = "font-09 pb-1 text-uppercase">{% trans "designed and developed by" %}<br><a class = "text-primary" href = "#">anthony rey</a></h2>
                    </div>
                </div>
            </div>
        </footer>
        
        <!-- js -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

reservation/templates/reservation/reservation_form.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% load l10n %}

{% load tz %}

{% block meta %}
<title>{% trans "Menu" %} | {% trans "Negus restaurant" %}</title>
{% endblock %}

{% block content %}
    <div class = "container">
        <form action = "{% url 'reservation:reservation_form' %}" method = "post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type = "submit">{% trans 'Contact Us'%}</button>
        </form>
    </div>
{% endblock %}